# Form implementation generated from reading ui file '/Users/ndb/Dev/python/python.scraper/ui/thread_container.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ThreadContainer(object):
    def setupUi(self, ThreadContainer):
        ThreadContainer.setObjectName("ThreadContainer")
        ThreadContainer.resize(480, 57)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ThreadContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.thread_label = QtWidgets.QLabel(parent=ThreadContainer)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.thread_label.setFont(font)
        self.thread_label.setStyleSheet("margin: 0;")
        self.thread_label.setIndent(0)
        self.thread_label.setObjectName("thread_label")
        self.verticalLayout.addWidget(self.thread_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.thread_input = QtWidgets.QLineEdit(parent=ThreadContainer)
        self.thread_input.setStyleSheet("margin: 0;\n"
"padding-left: 4px;")
        self.thread_input.setObjectName("thread_input")
        self.horizontalLayout_3.addWidget(self.thread_input)
        self.pushButton = QtWidgets.QPushButton(parent=ThreadContainer)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ThreadContainer)
        QtCore.QMetaObject.connectSlotsByName(ThreadContainer)

    def retranslateUi(self, ThreadContainer):
        _translate = QtCore.QCoreApplication.translate
        ThreadContainer.setWindowTitle(_translate("ThreadContainer", "Form"))
        self.thread_label.setText(_translate("ThreadContainer", "Thread 1"))
        self.pushButton.setText(_translate("ThreadContainer", "open_udd"))
